### ISSUE TITLE
Problem with Systemd

### ISSUE THREAD

**Issue by McGuten** [Bisa/factorio-init#11]
Hi guy

I have a little problem when i use your init, i do all steps and i can use "service factorio start" but no "systemctl factorio start"

When i do systemctl show me this error:
unknown operation 'factorio'.

You know what is the problem?

Thanks you a lot ^^

**Comment by Bisa** [comment]
"systemctl" and "service" cater to two different init systems, systemv and init.d

To set up systemctl you have to copy and/or modify the factorio.service.example into your own systemd unit (I guess since you already have "service factorio start" there is no need to use systemctl since they both do the same thing)

**Comment by McGuten** [comment]
oh, well, Thanks you ^^
