### ISSUE TITLE
Add Support for --headless

### ISSUE THREAD

**Issue by Jesavino** [Bisa/factorio-init#60]
Currently, if you add the --headless flag, the check to see if the PID is running does not successfully return. I'm posting this to possibly plan to pull and fix in the next couple weeks, but I want to make sure it is actually an issue and I'm not just missing anything.

**Comment by Bisa** [comment]
I'm trying to figure out your use case here; are you adding --headless to the extra bin args config option?
I noticed the headless binary does not have an option called '--headless', perhaps this is a corner case that arose due to the fact that I assumed all servers were running the headless binary any way =)

**Comment by Bisa** [comment]
Feel free to reopen this if you still have a problem =)
